from pathlib import Path

import nbformat as nbf


BASE_DIR = Path(__file__).resolve().parent

nb = nbf.v4.new_notebook()

nb["cells"] = [
    nbf.v4.new_markdown_cell(
        "# TensorFlow Hourly Rainfall Forecasting In Local Time\n\n"
        "This notebook trains a timestamp-driven MLP rainfall model for ESP32 deployment from "
        "`historical_weather_data_hourly.csv` in the `weather_irrigation_hourly` folder. "
        "Inference uses only the forecast timestamp, while training derives date and time features "
        "from local-time history before exporting TensorFlow Lite and C array artifacts."
    ),
    nbf.v4.new_markdown_cell("## 1. Imports"),
    nbf.v4.new_code_cell(
        "import json\n"
        "from pathlib import Path\n\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import tensorflow as tf\n"
        "from sklearn.metrics import accuracy_score, average_precision_score, brier_score_loss, f1_score, mean_absolute_error, precision_score, r2_score, recall_score, roc_auc_score, root_mean_squared_error\n"
        "from tensorflow.keras import Model\n"
        "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau\n"
        "from tensorflow.keras.layers import Dense, Dropout, Input\n\n"
        "tf.keras.utils.set_random_seed(42)\n"
        "np.random.seed(42)\n\n"
        "BASE_DIR = Path.cwd()\n"
        "DATA_PATH = BASE_DIR / 'historical_weather_data_hourly.csv'\n"
        "KERAS_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.keras'\n"
        "TFLITE_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.tflite'\n"
        "CC_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.cc'\n"
        "H_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.h'\n"
        "METRICS_PATH = BASE_DIR / 'hourly_rainfall_metrics.json'\n"
        "FEATURE_COLUMNS_PATH = BASE_DIR / 'hourly_feature_columns.json'\n"
        "X_MEAN_PATH = BASE_DIR / 'hourly_X_mean.npy'\n"
        "X_STD_PATH = BASE_DIR / 'hourly_X_std.npy'\n"
        "Y_AMOUNT_MEAN_PATH = BASE_DIR / 'hourly_y_amount_mean.npy'\n"
        "Y_AMOUNT_STD_PATH = BASE_DIR / 'hourly_y_amount_std.npy'\n"
        "RAIN_THRESHOLD_MM = 0.1\n"
        "C_ARRAY_NAME = 'hourly_rainfall_forecaster_tflite'\n"
    ),
    nbf.v4.new_markdown_cell("## 2. Load Local-Time Hourly History"),
    nbf.v4.new_code_cell(
        "if not DATA_PATH.exists():\n"
        "    raise FileNotFoundError(\n"
        "        'historical_weather_data_hourly.csv was not found. Run fetch_hourly_weather_data.py first.'\n"
        "    )\n\n"
        "df = pd.read_csv(DATA_PATH, parse_dates=['time'])\n"
        "df = df.sort_values('time').reset_index(drop=True)\n"
        "df['rain_mm'] = df['rain_mm'].clip(lower=0)\n"
        "df['rain_occurrence'] = (df['rain_mm'] >= RAIN_THRESHOLD_MM).astype(np.float32)\n"
        "print(df[['time', 'time_utc', 'rain_mm', 'precipitation_probability', 'cloud_cover_total_percent']].head())\n"
        "print(f'Loaded {len(df):,} hourly rows from {df.time.min()} to {df.time.max()}')\n"
    ),
    nbf.v4.new_markdown_cell("## 3. Calendar Feature Engineering"),
    nbf.v4.new_markdown_cell(
        "These features are designed to capture the structure that repeats on the calendar without leaking future rainfall values into the model. "
        "Rainfall tends to vary by season, time of day, and position in the year, so the notebook encodes those cycles explicitly. "
        "The `month`, `hour`, `day_of_year`, `day_of_week`, and `day_of_month` terms are represented with sine and cosine pairs so the model sees that the end of a cycle wraps smoothly back to the beginning. "
        "Second harmonics are added for hour and day-of-year because rainfall patterns are often not simple single-wave curves.\n\n"
        "The climatology features summarize the historical average rainfall amount and rainfall probability for the same month-hour and day-of-year-hour combinations. "
        "Those columns give the network a compact prior for the expected local weather regime at a timestamp before the dense layers learn non-linear interactions. "
        "`year_index` is included to let the model absorb slow multi-year drift, while `is_weekend` is a lightweight calendar flag that is cheap to test and can be removed later if it proves uninformative."
    ),
    nbf.v4.new_code_cell(
        "def cyclical_columns(values: pd.Series, period: float, prefix: str, harmonics: int = 1) -> dict[str, np.ndarray]:\n"
        "    angles = 2 * np.pi * values.to_numpy(dtype=float) / period\n"
        "    features = {}\n"
        "    for harmonic in range(1, harmonics + 1):\n"
        "        features[f'{prefix}_sin_{harmonic}'] = np.sin(harmonic * angles)\n"
        "        features[f'{prefix}_cos_{harmonic}'] = np.cos(harmonic * angles)\n"
        "    return features\n\n"
        "def build_climatology(frame: pd.DataFrame) -> dict:\n"
        "    train = frame.copy()\n"
        "    month_hour = train.groupby(['month_eat', 'hour_eat'])[['rain_mm', 'rain_occurrence']].mean().reset_index()\n"
        "    doy_hour = train.groupby(['day_of_year_eat', 'hour_eat'])[['rain_mm', 'rain_occurrence']].mean().reset_index()\n"
        "    return {\n"
        "        'month_hour_amount': {(int(r.month_eat), int(r.hour_eat)): float(r.rain_mm) for r in month_hour.itertuples()},\n"
        "        'month_hour_probability': {(int(r.month_eat), int(r.hour_eat)): float(r.rain_occurrence) for r in month_hour.itertuples()},\n"
        "        'doy_hour_amount': {(int(r.day_of_year_eat), int(r.hour_eat)): float(r.rain_mm) for r in doy_hour.itertuples()},\n"
        "        'doy_hour_probability': {(int(r.day_of_year_eat), int(r.hour_eat)): float(r.rain_occurrence) for r in doy_hour.itertuples()},\n"
        "        'global_amount': float(train['rain_mm'].mean()),\n"
        "        'global_probability': float(train['rain_occurrence'].mean()),\n"
        "    }\n\n"
        "def build_features(timestamps: pd.Series, climatology: dict) -> pd.DataFrame:\n"
        "    ts = pd.to_datetime(timestamps)\n"
        "    month = ts.dt.month\n"
        "    hour = ts.dt.hour\n"
        "    minute = ts.dt.minute\n"
        "    day_of_year = ts.dt.dayofyear\n"
        "    day_of_week = ts.dt.dayofweek\n"
        "    day_of_month = ts.dt.day\n"
        "    year_index = ts.dt.year - ts.dt.year.min()\n"
        "    month_hour_keys = list(zip(month, hour))\n"
        "    doy_hour_keys = list(zip(day_of_year, hour))\n\n"
        "    features = {\n"
        "        'year_index': year_index.to_numpy(dtype=float),\n"
        "        'is_weekend': (day_of_week >= 5).astype(float).to_numpy(),\n"
        "        'month_hour_amount_climatology': np.array([climatology['month_hour_amount'].get(k, climatology['global_amount']) for k in month_hour_keys]),\n"
        "        'month_hour_probability_climatology': np.array([climatology['month_hour_probability'].get(k, climatology['global_probability']) for k in month_hour_keys]),\n"
        "        'doy_hour_amount_climatology': np.array([climatology['doy_hour_amount'].get(k, climatology['global_amount']) for k in doy_hour_keys]),\n"
        "        'doy_hour_probability_climatology': np.array([climatology['doy_hour_probability'].get(k, climatology['global_probability']) for k in doy_hour_keys]),\n"
        "    }\n"
        "    features.update(cyclical_columns(month, 12.0, 'month'))\n"
        "    features.update(cyclical_columns(hour + minute / 60.0, 24.0, 'hour', harmonics=2))\n"
        "    features.update(cyclical_columns(day_of_year, 365.25, 'doy', harmonics=2))\n"
        "    features.update(cyclical_columns(day_of_week, 7.0, 'dow'))\n"
        "    features.update(cyclical_columns(day_of_month, 31.0, 'dom'))\n"
        "    return pd.DataFrame(features, index=ts.index).astype(np.float32)\n"
    ),
    nbf.v4.new_code_cell(
        "calendar_diagnostics = df.copy()\n"
        "calendar_diagnostics['rolling_rain_probability'] = (\n"
        "    calendar_diagnostics.groupby('day_of_year_eat')['rain_occurrence']\n"
        "    .mean()\n"
        "    .rolling(window=21, center=True, min_periods=1)\n"
        "    .mean()\n"
        ")\n"
        "month_hour_probability = df.pivot_table(\n"
        "    index='month_eat',\n"
        "    columns='hour_eat',\n"
        "    values='rain_occurrence',\n"
        "    aggfunc='mean'\n"
        ")\n\n"
        "fig, axes = plt.subplots(2, 2, figsize=(15, 10), constrained_layout=True)\n"
        "df.groupby('hour_eat')['rain_occurrence'].mean().plot(ax=axes[0, 0], marker='o', color='tab:blue')\n"
        "axes[0, 0].set_title('Rain Probability By Hour')\n"
        "axes[0, 0].set_xlabel('Hour of day')\n"
        "axes[0, 0].set_ylabel('Probability of rain')\n\n"
        "df.groupby('month_eat')['rain_mm'].mean().plot(ax=axes[0, 1], marker='o', color='tab:green')\n"
        "axes[0, 1].set_title('Average Rainfall Amount By Month')\n"
        "axes[0, 1].set_xlabel('Month')\n"
        "axes[0, 1].set_ylabel('Rainfall (mm)')\n\n"
        "calendar_diagnostics['rolling_rain_probability'].plot(ax=axes[1, 0], color='tab:orange')\n"
        "axes[1, 0].set_title('Smoothed Rain Probability Across Day Of Year')\n"
        "axes[1, 0].set_xlabel('Day of year')\n"
        "axes[1, 0].set_ylabel('Probability of rain')\n\n"
        "im = axes[1, 1].imshow(month_hour_probability.to_numpy(), aspect='auto', cmap='Blues', origin='lower')\n"
        "axes[1, 1].set_title('Month-Hour Rain Probability Heatmap')\n"
        "axes[1, 1].set_xlabel('Hour of day')\n"
        "axes[1, 1].set_ylabel('Month')\n"
        "axes[1, 1].set_xticks(range(0, 24, 3))\n"
        "axes[1, 1].set_yticks(range(12))\n"
        "axes[1, 1].set_yticklabels(month_hour_probability.index.astype(int))\n"
        "fig.colorbar(im, ax=axes[1, 1], label='Probability of rain')\n"
        "plt.show()\n\n"
        "print('Feature rationale summary:')\n"
        "print('- Hour features capture the strong within-day change visible in rain probability.')\n"
        "print('- Month and day-of-year features capture the seasonal shift in rainfall intensity and frequency.')\n"
        "print('- Climatology features summarize the month-hour and day-of-year-hour structure shown above.')\n"
        "print('- Cyclical encoding avoids artificial jumps such as 23:00 to 00:00 or December to January.')\n"
    ),
    nbf.v4.new_markdown_cell("## 4. Time-Based Split And Scaling"),
    nbf.v4.new_markdown_cell(
        "The train-test split is chronological instead of random because forecasting must use the past to predict the future. "
        "A random split would leak future seasonal states into training and make evaluation look better than real deployment. "
        "Using the first 80% of the timeline for training and the latest 20% for testing gives a more realistic estimate of how the model behaves on unseen future months.\n\n"
        "Scaling is fit on the training window only and then reused for the test window. "
        "That keeps the preprocessing aligned with deployment, where future data statistics are not known in advance. "
        "The target rainfall amount is log-scaled before standardization because hourly rain is highly right-skewed: many dry hours and a small number of heavy-rain events. "
        "The log transform compresses those spikes so the regression loss is less dominated by a few extreme hours."
    ),
    nbf.v4.new_code_cell(
        "split_idx = int(len(df) * 0.8)\n"
        "train_df = df.iloc[:split_idx].copy()\n"
        "test_df = df.iloc[split_idx:].copy()\n"
        "climatology = build_climatology(train_df)\n\n"
        "X_train_df = build_features(train_df['time'], climatology)\n"
        "X_test_df = build_features(test_df['time'], climatology)\n"
        "feature_columns = list(X_train_df.columns)\n\n"
        "X_train = X_train_df.to_numpy(dtype=np.float32)\n"
        "X_test = X_test_df.to_numpy(dtype=np.float32)\n"
        "y_train_amount = train_df['rain_mm'].to_numpy(dtype=np.float32)\n"
        "y_test_amount = test_df['rain_mm'].to_numpy(dtype=np.float32)\n"
        "y_train_rain = train_df['rain_occurrence'].to_numpy(dtype=np.float32)\n"
        "y_test_rain = test_df['rain_occurrence'].to_numpy(dtype=np.float32)\n\n"
        "month_hour_keys_test = list(zip(test_df['month_eat'], test_df['hour_eat']))\n"
        "baseline_amount = np.array([climatology['month_hour_amount'].get(k, climatology['global_amount']) for k in month_hour_keys_test], dtype=np.float32)\n"
        "baseline_probability = np.array([climatology['month_hour_probability'].get(k, climatology['global_probability']) for k in month_hour_keys_test], dtype=np.float32)\n"
        "persistence_amount_last_hour = df['rain_mm'].shift(1).iloc[split_idx:].to_numpy(dtype=np.float32)\n"
        "persistence_probability_last_hour = df['rain_occurrence'].shift(1).iloc[split_idx:].to_numpy(dtype=np.float32)\n\n"
        "X_mean = X_train.mean(axis=0)\n"
        "X_std = X_train.std(axis=0)\n"
        "X_std[X_std == 0] = 1e-6\n"
        "X_train_scaled = (X_train - X_mean) / X_std\n"
        "X_test_scaled = (X_test - X_mean) / X_std\n\n"
        "y_train_amount_log = np.log1p(y_train_amount)\n"
        "y_amount_mean = y_train_amount_log.mean()\n"
        "y_amount_std = y_train_amount_log.std()\n"
        "if y_amount_std == 0:\n"
        "    y_amount_std = 1e-6\n"
        "y_train_amount_scaled = ((y_train_amount_log - y_amount_mean) / y_amount_std).astype(np.float32)\n\n"
        "np.save(X_MEAN_PATH, X_mean)\n"
        "np.save(X_STD_PATH, X_std)\n"
        "np.save(Y_AMOUNT_MEAN_PATH, np.array([y_amount_mean], dtype=np.float32))\n"
        "np.save(Y_AMOUNT_STD_PATH, np.array([y_amount_std], dtype=np.float32))\n"
        "FEATURE_COLUMNS_PATH.write_text(json.dumps(feature_columns, indent=2))\n"
        "print(f'Train rows: {len(train_df):,}, test rows: {len(test_df):,}')\n"
        "print(f'Feature count: {X_train_scaled.shape[1]}')\n"
    ),
    nbf.v4.new_code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(15, 10), constrained_layout=True)\n\n"
        "axes[0, 0].plot(df['time'], df['rain_mm'], color='tab:blue', linewidth=0.8)\n"
        "axes[0, 0].axvline(df.loc[split_idx, 'time'], color='tab:red', linestyle='--', label='Train/test split')\n"
        "axes[0, 0].set_title('Chronological Split On Rainfall Timeline')\n"
        "axes[0, 0].set_xlabel('Timestamp')\n"
        "axes[0, 0].set_ylabel('Rainfall (mm)')\n"
        "axes[0, 0].legend()\n\n"
        "axes[0, 1].hist(y_train_amount, bins=50, alpha=0.65, label='Raw train target', color='tab:blue')\n"
        "axes[0, 1].hist(np.log1p(y_train_amount), bins=50, alpha=0.65, label='log1p(train target)', color='tab:orange')\n"
        "axes[0, 1].set_title('Why Log-Scale The Rainfall Target')\n"
        "axes[0, 1].set_xlabel('Target value')\n"
        "axes[0, 1].set_ylabel('Count')\n"
        "axes[0, 1].legend()\n\n"
        "sample_feature_names = feature_columns[:4]\n"
        "sample_indices = [feature_columns.index(name) for name in sample_feature_names]\n"
        "x = np.arange(len(sample_feature_names))\n"
        "train_feature_mean = X_train[:, sample_indices].mean(axis=0)\n"
        "train_feature_std = X_train_scaled[:, sample_indices].std(axis=0)\n"
        "test_feature_mean_scaled = X_test_scaled[:, sample_indices].mean(axis=0)\n"
        "axes[1, 0].bar(x - 0.2, train_feature_mean, width=0.4, label='Raw train mean', color='tab:green')\n"
        "axes[1, 0].bar(x + 0.2, X_mean[sample_indices], width=0.4, label='Saved scaler mean', color='tab:purple')\n"
        "axes[1, 0].set_title('Scaler Parameters Come From Training Data')\n"
        "axes[1, 0].set_xticks(x)\n"
        "axes[1, 0].set_xticklabels(sample_feature_names, rotation=20, ha='right')\n"
        "axes[1, 0].legend()\n\n"
        "axes[1, 1].bar(x - 0.2, train_feature_std, width=0.4, label='Train scaled std', color='tab:gray')\n"
        "axes[1, 1].bar(x + 0.2, test_feature_mean_scaled, width=0.4, label='Test scaled mean', color='tab:brown')\n"
        "axes[1, 1].axhline(0.0, color='black', linewidth=0.8)\n"
        "axes[1, 1].set_title('Training Centers The Features; Test Remains Unseen')\n"
        "axes[1, 1].set_xticks(x)\n"
        "axes[1, 1].set_xticklabels(sample_feature_names, rotation=20, ha='right')\n"
        "axes[1, 1].legend()\n"
        "plt.show()\n\n"
        "print('Split and scaling rationale summary:')\n"
        "print('- The split is chronological so evaluation reflects true forward-looking forecasting.')\n"
        "print('- Scaling parameters are estimated on the training window only to avoid look-ahead leakage.')\n"
        "print('- The test set is intentionally not re-centered to zero; any shift there reflects real distribution change.')\n"
        "print('- log1p rainfall scaling reduces the dominance of rare heavy-rain hours in the regression loss.')\n"
    ),
    nbf.v4.new_markdown_cell("## 5. TensorFlow MLP Model"),
    nbf.v4.new_code_cell(
        "inputs = Input(shape=(X_train_scaled.shape[1],), name='calendar_features')\n"
        "x = Dense(64, activation='relu')(inputs)\n"
        "x = Dropout(0.15)(x)\n"
        "x = Dense(32, activation='relu')(x)\n"
        "x = Dense(16, activation='relu')(x)\n"
        "amount_output = Dense(1, name='amount_output')(x)\n"
        "probability_output = Dense(1, activation='sigmoid', name='probability_output')(x)\n\n"
        "model = Model(inputs=inputs, outputs=[amount_output, probability_output])\n"
        "model.compile(\n"
        "    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n"
        "    loss={\n"
        "        'amount_output': 'mse',\n"
        "        'probability_output': 'binary_crossentropy',\n"
        "    },\n"
        "    loss_weights={\n"
        "        'amount_output': 1.0,\n"
        "        'probability_output': 0.7,\n"
        "    },\n"
        ")\n"
        "model.summary()\n"
    ),
    nbf.v4.new_markdown_cell("## 6. Train"),
    nbf.v4.new_code_cell(
        "callbacks = [\n"
        "    EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True),\n"
        "    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8, min_lr=1e-5),\n"
        "]\n\n"
        "history = model.fit(\n"
        "    X_train_scaled,\n"
        "    {\n"
        "        'amount_output': y_train_amount_scaled,\n"
        "        'probability_output': y_train_rain,\n"
        "    },\n"
        "    validation_split=0.2,\n"
        "    epochs=250,\n"
        "    batch_size=32,\n"
        "    verbose=0,\n"
        "    callbacks=callbacks,\n"
        ")\n\n"
        "print(f\"Training stopped after {len(history.history['loss'])} epochs.\")\n"
        "print(f\"Best val_loss: {min(history.history['val_loss']):.4f}\")\n"
    ),
    nbf.v4.new_markdown_cell("## 7. Evaluate"),
    nbf.v4.new_code_cell(
        "amount_pred_scaled, probability_pred = model.predict(X_test_scaled, verbose=0)\n"
        "amount_pred_scaled = amount_pred_scaled.reshape(-1)\n"
        "probability_pred = probability_pred.reshape(-1)\n"
        "amount_pred = np.expm1((amount_pred_scaled * y_amount_std) + y_amount_mean).clip(min=0)\n"
        "rainy_mask = y_test_amount >= RAIN_THRESHOLD_MM\n\n"
        "def safe_float(value):\n"
        "    return None if pd.isna(value) else float(value)\n\n"
        "def amount_metrics(y_true, y_pred):\n"
        "    rainy_true = y_true[rainy_mask]\n"
        "    rainy_pred = y_pred[rainy_mask]\n"
        "    return {\n"
        "        'mae_mm': float(mean_absolute_error(y_true, y_pred)),\n"
        "        'rmse_mm': float(root_mean_squared_error(y_true, y_pred)),\n"
        "        'r2': float(r2_score(y_true, y_pred)),\n"
        "        'rainy_hours_count': int(rainy_mask.sum()),\n"
        "        'rainy_mae_mm': safe_float(mean_absolute_error(rainy_true, rainy_pred)) if len(rainy_true) else None,\n"
        "        'rainy_rmse_mm': safe_float(root_mean_squared_error(rainy_true, rainy_pred)) if len(rainy_true) else None,\n"
        "    }\n\n"
        "def probability_metrics(y_true, y_prob):\n"
        "    y_pred = (y_prob >= 0.5).astype(np.float32)\n"
        "    positives = int(y_true.sum())\n"
        "    negatives = int(len(y_true) - positives)\n"
        "    tp = int(((y_true == 1) & (y_pred == 1)).sum())\n"
        "    tn = int(((y_true == 0) & (y_pred == 0)).sum())\n"
        "    fp = int(((y_true == 0) & (y_pred == 1)).sum())\n"
        "    fn = int(((y_true == 1) & (y_pred == 0)).sum())\n"
        "    roc_auc = roc_auc_score(y_true, y_prob) if positives and negatives else np.nan\n"
        "    pr_auc = average_precision_score(y_true, y_prob) if positives else np.nan\n"
        "    return {\n"
        "        'brier_score': float(brier_score_loss(y_true, y_prob)),\n"
        "        'accuracy': float(accuracy_score(y_true, y_pred)),\n"
        "        'precision': float(precision_score(y_true, y_pred, zero_division=0)),\n"
        "        'recall': float(recall_score(y_true, y_pred, zero_division=0)),\n"
        "        'f1': float(f1_score(y_true, y_pred, zero_division=0)),\n"
        "        'roc_auc': safe_float(roc_auc),\n"
        "        'pr_auc': safe_float(pr_auc),\n"
        "        'positive_hours': positives,\n"
        "        'negative_hours': negatives,\n"
        "        'tp': tp,\n"
        "        'tn': tn,\n"
        "        'fp': fp,\n"
        "        'fn': fn,\n"
        "    }\n\n"
        "metrics = {\n"
        "    'train_rows': int(len(train_df)),\n"
        "    'test_rows': int(len(test_df)),\n"
        "    'feature_columns': feature_columns,\n"
        "    'amount_models': {\n"
        "        'mlp': amount_metrics(y_test_amount, amount_pred),\n"
        "        'climatology_month_hour': amount_metrics(y_test_amount, baseline_amount),\n"
        "        'persistence_last_hour': amount_metrics(y_test_amount, persistence_amount_last_hour),\n"
        "    },\n"
        "    'probability_models': {\n"
        "        'mlp': probability_metrics(y_test_rain, probability_pred),\n"
        "        'climatology_month_hour': probability_metrics(y_test_rain, baseline_probability),\n"
        "        'persistence_last_hour': probability_metrics(y_test_rain, persistence_probability_last_hour),\n"
        "    },\n"
        "}\n"
        "metrics['selected_amount_model'] = min(\n"
        "    metrics['amount_models'],\n"
        "    key=lambda name: (\n"
        "        metrics['amount_models'][name]['rmse_mm'],\n"
        "        metrics['amount_models'][name]['mae_mm'],\n"
        "    ),\n"
        ")\n"
        "metrics['selected_probability_model'] = min(\n"
        "    metrics['probability_models'],\n"
        "    key=lambda name: (\n"
        "        metrics['probability_models'][name]['brier_score'],\n"
        "        -metrics['probability_models'][name]['f1'],\n"
        "    ),\n"
        ")\n"
        "print(json.dumps(metrics, indent=2))\n"
    ),
    nbf.v4.new_markdown_cell("## 8. Export Keras, TFLite, And ESP32 Artifacts"),
    nbf.v4.new_code_cell(
        "def convert_tflite_to_c_array(tflite_path: Path, c_file_path: Path, h_file_path: Path, array_name: str):\n"
        "    tflite_content = tflite_path.read_bytes()\n"
        "    hex_array = [f'0x{byte:02x}' for byte in tflite_content]\n\n"
        "    with c_file_path.open('w') as c_file:\n"
        "        c_file.write(f'#include \"{h_file_path.name}\"\\n\\n')\n"
        "        c_file.write(f'const unsigned char {array_name}[] = {{\\n')\n"
        "        for idx in range(0, len(hex_array), 12):\n"
        "            c_file.write('  ' + ', '.join(hex_array[idx:idx + 12]) + ',\\n')\n"
        "        c_file.write('};\\n\\n')\n"
        "        c_file.write(f'const int {array_name}_len = {len(tflite_content)};\\n')\n\n"
        "    with h_file_path.open('w') as h_file:\n"
        "        guard = h_file_path.stem.upper() + '_H'\n"
        "        h_file.write(f'#ifndef {guard}\\n')\n"
        "        h_file.write(f'#define {guard}\\n\\n')\n"
        "        h_file.write(f'extern const unsigned char {array_name}[];\\n')\n"
        "        h_file.write(f'extern const int {array_name}_len;\\n\\n')\n"
        "        h_file.write(f'#endif  // {guard}\\n')\n\n"
        "model.save(KERAS_MODEL_PATH)\n"
        "converter = tf.lite.TFLiteConverter.from_keras_model(model)\n"
        "converter.optimizations = [tf.lite.Optimize.DEFAULT]\n"
        "tflite_model = converter.convert()\n"
        "TFLITE_MODEL_PATH.write_bytes(tflite_model)\n"
        "convert_tflite_to_c_array(TFLITE_MODEL_PATH, CC_MODEL_PATH, H_MODEL_PATH, C_ARRAY_NAME)\n"
        "METRICS_PATH.write_text(json.dumps(metrics, indent=2))\n\n"
        "print(f'Saved {KERAS_MODEL_PATH.name}')\n"
        "print(f'Saved {TFLITE_MODEL_PATH.name} ({len(tflite_model)} bytes)')\n"
        "print(f'Saved {CC_MODEL_PATH.name}')\n"
        "print(f'Saved {H_MODEL_PATH.name}')\n"
        "print(f'Saved {METRICS_PATH.name}')\n"
    ),
    nbf.v4.new_markdown_cell("## 9. Inference Helper"),
    nbf.v4.new_code_cell(
        "def forecast_hourly_rainfall(timestamps):\n"
        "    ts = pd.Series(pd.to_datetime(timestamps), name='forecast_time')\n"
        "    X_future_df = build_features(ts, climatology)\n"
        "    X_future = X_future_df[feature_columns].to_numpy(dtype=np.float32)\n"
        "    X_future_scaled = (X_future - X_mean) / X_std\n"
        "    amount_scaled, probability = model.predict(X_future_scaled, verbose=0)\n"
        "    amount_scaled = amount_scaled.reshape(-1)\n"
        "    probability = probability.reshape(-1)\n"
        "    amount = np.expm1((amount_scaled * y_amount_std) + y_amount_mean).clip(min=0)\n"
        "    return pd.DataFrame({\n"
        "        'forecast_time': ts,\n"
        "        'expected_rainfall_mm': amount,\n"
        "        'probability_of_rain': probability,\n"
        "        'rain_likely': probability >= 0.5,\n"
        "    })\n\n"
        "forecast_hourly_rainfall(['2026-03-10 06:00:00', '2026-03-10 14:00:00'])\n"
    ),
]

with open(BASE_DIR / "hourly_rainfall_forecasting.ipynb", "w") as f:
    nbf.write(nb, f)
