from pathlib import Path

import nbformat as nbf


BASE_DIR = Path(__file__).resolve().parent

nb = nbf.v4.new_notebook()

nb["cells"] = [
    nbf.v4.new_markdown_cell(
        "# TensorFlow Hourly Rainfall Forecasting In EAT\n\n"
        "This notebook trains an hourly rainfall model for ESP32 deployment from "
        "`historical_weather_data_hourly.csv` in the `weather_irrigation_hourly` folder. "
        "All timestamps are normalized to EAT (`Africa/Nairobi`) before feature engineering, "
        "and the final model is exported to TensorFlow Lite."
    ),
    nbf.v4.new_markdown_cell("## 1. Imports"),
    nbf.v4.new_code_cell(
        "import json\n"
        "from pathlib import Path\n\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import tensorflow as tf\n"
        "from sklearn.metrics import accuracy_score, brier_score_loss, mean_absolute_error, r2_score, root_mean_squared_error\n"
        "from tensorflow.keras import Model\n"
        "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau\n"
        "from tensorflow.keras.layers import Dense, Dropout, Input\n\n"
        "tf.keras.utils.set_random_seed(42)\n"
        "np.random.seed(42)\n\n"
        "BASE_DIR = Path.cwd()\n"
        "DATA_PATH = BASE_DIR / 'historical_weather_data_hourly.csv'\n"
        "KERAS_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.keras'\n"
        "TFLITE_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.tflite'\n"
        "METRICS_PATH = BASE_DIR / 'hourly_rainfall_metrics.json'\n"
        "FEATURE_COLUMNS_PATH = BASE_DIR / 'hourly_feature_columns.json'\n"
        "X_MEAN_PATH = BASE_DIR / 'hourly_X_mean.npy'\n"
        "X_STD_PATH = BASE_DIR / 'hourly_X_std.npy'\n"
        "Y_AMOUNT_MEAN_PATH = BASE_DIR / 'hourly_y_amount_mean.npy'\n"
        "Y_AMOUNT_STD_PATH = BASE_DIR / 'hourly_y_amount_std.npy'\n"
        "RAIN_THRESHOLD_MM = 0.1\n"
    ),
    nbf.v4.new_markdown_cell("## 2. Load EAT-Normalized Hourly History"),
    nbf.v4.new_code_cell(
        "if not DATA_PATH.exists():\n"
        "    raise FileNotFoundError(\n"
        "        'historical_weather_data_hourly.csv was not found. Run fetch_hourly_weather_data.py first.'\n"
        "    )\n\n"
        "df = pd.read_csv(DATA_PATH, parse_dates=['time'])\n"
        "df = df.sort_values('time').reset_index(drop=True)\n"
        "df['rain_mm'] = df['rain_mm'].clip(lower=0)\n"
        "df['rain_occurrence'] = (df['rain_mm'] >= RAIN_THRESHOLD_MM).astype(np.float32)\n"
        "print(df[['time', 'time_utc', 'rain_mm', 'precipitation_probability', 'cloud_cover_total_percent']].head())\n"
        "print(f'Loaded {len(df):,} hourly rows from {df.time.min()} to {df.time.max()}')\n"
    ),
    nbf.v4.new_markdown_cell("## 3. Calendar Feature Engineering"),
    nbf.v4.new_code_cell(
        "def cyclical_columns(values: pd.Series, period: float, prefix: str, harmonics: int = 1) -> dict[str, np.ndarray]:\n"
        "    angles = 2 * np.pi * values.to_numpy(dtype=float) / period\n"
        "    features = {}\n"
        "    for harmonic in range(1, harmonics + 1):\n"
        "        features[f'{prefix}_sin_{harmonic}'] = np.sin(harmonic * angles)\n"
        "        features[f'{prefix}_cos_{harmonic}'] = np.cos(harmonic * angles)\n"
        "    return features\n\n"
        "def build_climatology(frame: pd.DataFrame) -> dict:\n"
        "    train = frame.copy()\n"
        "    month_hour = train.groupby(['month_eat', 'hour_eat'])[['rain_mm', 'rain_occurrence']].mean().reset_index()\n"
        "    doy_hour = train.groupby(['day_of_year_eat', 'hour_eat'])[['rain_mm', 'rain_occurrence']].mean().reset_index()\n"
        "    return {\n"
        "        'month_hour_amount': {(int(r.month_eat), int(r.hour_eat)): float(r.rain_mm) for r in month_hour.itertuples()},\n"
        "        'month_hour_probability': {(int(r.month_eat), int(r.hour_eat)): float(r.rain_occurrence) for r in month_hour.itertuples()},\n"
        "        'doy_hour_amount': {(int(r.day_of_year_eat), int(r.hour_eat)): float(r.rain_mm) for r in doy_hour.itertuples()},\n"
        "        'doy_hour_probability': {(int(r.day_of_year_eat), int(r.hour_eat)): float(r.rain_occurrence) for r in doy_hour.itertuples()},\n"
        "        'global_amount': float(train['rain_mm'].mean()),\n"
        "        'global_probability': float(train['rain_occurrence'].mean()),\n"
        "    }\n\n"
        "def build_features(timestamps: pd.Series, climatology: dict) -> pd.DataFrame:\n"
        "    ts = pd.to_datetime(timestamps)\n"
        "    month = ts.dt.month\n"
        "    hour = ts.dt.hour\n"
        "    minute = ts.dt.minute\n"
        "    day_of_year = ts.dt.dayofyear\n"
        "    day_of_week = ts.dt.dayofweek\n"
        "    day_of_month = ts.dt.day\n"
        "    year_index = ts.dt.year - ts.dt.year.min()\n"
        "    month_hour_keys = list(zip(month, hour))\n"
        "    doy_hour_keys = list(zip(day_of_year, hour))\n\n"
        "    features = {\n"
        "        'year_index': year_index.to_numpy(dtype=float),\n"
        "        'is_weekend': (day_of_week >= 5).astype(float).to_numpy(),\n"
        "        'month_hour_amount_climatology': np.array([climatology['month_hour_amount'].get(k, climatology['global_amount']) for k in month_hour_keys]),\n"
        "        'month_hour_probability_climatology': np.array([climatology['month_hour_probability'].get(k, climatology['global_probability']) for k in month_hour_keys]),\n"
        "        'doy_hour_amount_climatology': np.array([climatology['doy_hour_amount'].get(k, climatology['global_amount']) for k in doy_hour_keys]),\n"
        "        'doy_hour_probability_climatology': np.array([climatology['doy_hour_probability'].get(k, climatology['global_probability']) for k in doy_hour_keys]),\n"
        "    }\n"
        "    features.update(cyclical_columns(month, 12.0, 'month'))\n"
        "    features.update(cyclical_columns(hour + minute / 60.0, 24.0, 'hour', harmonics=2))\n"
        "    features.update(cyclical_columns(day_of_year, 365.25, 'doy', harmonics=2))\n"
        "    features.update(cyclical_columns(day_of_week, 7.0, 'dow'))\n"
        "    features.update(cyclical_columns(day_of_month, 31.0, 'dom'))\n"
        "    return pd.DataFrame(features, index=ts.index).astype(np.float32)\n"
    ),
    nbf.v4.new_markdown_cell("## 4. Time-Based Split And Scaling"),
    nbf.v4.new_code_cell(
        "split_idx = int(len(df) * 0.8)\n"
        "train_df = df.iloc[:split_idx].copy()\n"
        "test_df = df.iloc[split_idx:].copy()\n"
        "climatology = build_climatology(train_df)\n\n"
        "X_train_df = build_features(train_df['time'], climatology)\n"
        "X_test_df = build_features(test_df['time'], climatology)\n"
        "feature_columns = list(X_train_df.columns)\n\n"
        "X_train = X_train_df.to_numpy(dtype=np.float32)\n"
        "X_test = X_test_df.to_numpy(dtype=np.float32)\n"
        "y_train_amount = train_df['rain_mm'].to_numpy(dtype=np.float32)\n"
        "y_test_amount = test_df['rain_mm'].to_numpy(dtype=np.float32)\n"
        "y_train_rain = train_df['rain_occurrence'].to_numpy(dtype=np.float32)\n"
        "y_test_rain = test_df['rain_occurrence'].to_numpy(dtype=np.float32)\n\n"
        "month_hour_keys_test = list(zip(test_df['month_eat'], test_df['hour_eat']))\n"
        "baseline_amount = np.array([climatology['month_hour_amount'].get(k, climatology['global_amount']) for k in month_hour_keys_test], dtype=np.float32)\n"
        "baseline_probability = np.array([climatology['month_hour_probability'].get(k, climatology['global_probability']) for k in month_hour_keys_test], dtype=np.float32)\n\n"
        "X_mean = X_train.mean(axis=0)\n"
        "X_std = X_train.std(axis=0)\n"
        "X_std[X_std == 0] = 1e-6\n"
        "X_train_scaled = (X_train - X_mean) / X_std\n"
        "X_test_scaled = (X_test - X_mean) / X_std\n\n"
        "y_train_amount_log = np.log1p(y_train_amount)\n"
        "y_test_amount_log = np.log1p(y_test_amount)\n"
        "y_amount_mean = y_train_amount_log.mean()\n"
        "y_amount_std = y_train_amount_log.std()\n"
        "if y_amount_std == 0:\n"
        "    y_amount_std = 1e-6\n"
        "y_train_amount_scaled = ((y_train_amount_log - y_amount_mean) / y_amount_std).astype(np.float32)\n\n"
        "np.save(X_MEAN_PATH, X_mean)\n"
        "np.save(X_STD_PATH, X_std)\n"
        "np.save(Y_AMOUNT_MEAN_PATH, np.array([y_amount_mean], dtype=np.float32))\n"
        "np.save(Y_AMOUNT_STD_PATH, np.array([y_amount_std], dtype=np.float32))\n"
        "FEATURE_COLUMNS_PATH.write_text(json.dumps(feature_columns, indent=2))\n"
    ),
    nbf.v4.new_markdown_cell("## 5. TensorFlow Model"),
    nbf.v4.new_code_cell(
        "inputs = Input(shape=(X_train_scaled.shape[1],), name='calendar_features')\n"
        "x = Dense(64, activation='relu')(inputs)\n"
        "x = Dropout(0.15)(x)\n"
        "x = Dense(32, activation='relu')(x)\n"
        "x = Dense(16, activation='relu')(x)\n"
        "amount_output = Dense(1, name='amount_output')(x)\n"
        "probability_output = Dense(1, activation='sigmoid', name='probability_output')(x)\n\n"
        "model = Model(inputs=inputs, outputs=[amount_output, probability_output])\n"
        "model.compile(\n"
        "    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n"
        "    loss={\n"
        "        'amount_output': 'mse',\n"
        "        'probability_output': 'binary_crossentropy',\n"
        "    },\n"
        "    loss_weights={\n"
        "        'amount_output': 1.0,\n"
        "        'probability_output': 0.7,\n"
        "    },\n"
        ")\n"
        "model.summary()\n"
    ),
    nbf.v4.new_markdown_cell("## 6. Train"),
    nbf.v4.new_code_cell(
        "callbacks = [\n"
        "    EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True),\n"
        "    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8, min_lr=1e-5),\n"
        "]\n\n"
        "history = model.fit(\n"
        "    X_train_scaled,\n"
        "    {\n"
        "        'amount_output': y_train_amount_scaled,\n"
        "        'probability_output': y_train_rain,\n"
        "    },\n"
        "    validation_split=0.2,\n"
        "    epochs=250,\n"
        "    batch_size=32,\n"
        "    verbose=0,\n"
        "    callbacks=callbacks,\n"
        ")\n\n"
        "print(f\"Training stopped after {len(history.history['loss'])} epochs.\")\n"
        "print(f\"Best val_loss: {min(history.history['val_loss']):.4f}\")\n"
    ),
    nbf.v4.new_markdown_cell("## 7. Evaluate Against Climatology"),
    nbf.v4.new_code_cell(
        "amount_pred_scaled, probability_pred = model.predict(X_test_scaled, verbose=0)\n"
        "amount_pred_scaled = amount_pred_scaled.reshape(-1)\n"
        "probability_pred = probability_pred.reshape(-1)\n"
        "amount_pred = np.expm1((amount_pred_scaled * y_amount_std) + y_amount_mean).clip(min=0)\n\n"
        "def amount_metrics(y_true, y_pred):\n"
        "    return {\n"
        "        'mae_mm': float(mean_absolute_error(y_true, y_pred)),\n"
        "        'rmse_mm': float(root_mean_squared_error(y_true, y_pred)),\n"
        "        'r2': float(r2_score(y_true, y_pred)),\n"
        "    }\n\n"
        "def probability_metrics(y_true, y_prob):\n"
        "    return {\n"
        "        'brier_score': float(brier_score_loss(y_true, y_prob)),\n"
        "        'accuracy': float(accuracy_score(y_true, y_prob >= 0.5)),\n"
        "    }\n\n"
        "metrics = {\n"
        "    'train_rows': int(len(train_df)),\n"
        "    'test_rows': int(len(test_df)),\n"
        "    'tensorflow_amount': amount_metrics(y_test_amount, amount_pred),\n"
        "    'baseline_amount': amount_metrics(y_test_amount, baseline_amount),\n"
        "    'tensorflow_probability': probability_metrics(y_test_rain, probability_pred),\n"
        "    'baseline_probability': probability_metrics(y_test_rain, baseline_probability),\n"
        "}\n"
        "metrics['selected_amount_model'] = (\n"
        "    'tensorflow_amount_model'\n"
        "    if metrics['tensorflow_amount']['mae_mm'] < metrics['baseline_amount']['mae_mm']\n"
        "    and metrics['tensorflow_amount']['rmse_mm'] < metrics['baseline_amount']['rmse_mm']\n"
        "    else 'month_hour_climatology'\n"
        ")\n"
        "metrics['selected_probability_model'] = (\n"
        "    'tensorflow_probability_model'\n"
        "    if metrics['tensorflow_probability']['brier_score'] < metrics['baseline_probability']['brier_score']\n"
        "    else 'month_hour_climatology'\n"
        ")\n"
        "print(json.dumps(metrics, indent=2))\n"
    ),
    nbf.v4.new_markdown_cell("## 8. Export Keras And TFLite Artifacts"),
    nbf.v4.new_code_cell(
        "model.save(KERAS_MODEL_PATH)\n"
        "converter = tf.lite.TFLiteConverter.from_keras_model(model)\n"
        "converter.optimizations = [tf.lite.Optimize.DEFAULT]\n"
        "tflite_model = converter.convert()\n"
        "TFLITE_MODEL_PATH.write_bytes(tflite_model)\n"
        "METRICS_PATH.write_text(json.dumps(metrics, indent=2))\n\n"
        "print(f'Saved {KERAS_MODEL_PATH.name}')\n"
        "print(f'Saved {TFLITE_MODEL_PATH.name} ({len(tflite_model)} bytes)')\n"
        "print(f'Saved {METRICS_PATH.name}')\n"
    ),
    nbf.v4.new_markdown_cell("## 9. Inference Helper"),
    nbf.v4.new_code_cell(
        "def forecast_hourly_rainfall(timestamps):\n"
        "    ts = pd.Series(pd.to_datetime(timestamps), name='forecast_time')\n"
        "    X_future_df = build_features(ts, climatology)\n"
        "    X_future = X_future_df[feature_columns].to_numpy(dtype=np.float32)\n"
        "    X_future_scaled = (X_future - X_mean) / X_std\n"
        "    amount_scaled, probability = model.predict(X_future_scaled, verbose=0)\n"
        "    amount_scaled = amount_scaled.reshape(-1)\n"
        "    probability = probability.reshape(-1)\n"
        "    amount = np.expm1((amount_scaled * y_amount_std) + y_amount_mean).clip(min=0)\n"
        "    return pd.DataFrame({\n"
        "        'forecast_time': ts,\n"
        "        'expected_rainfall_mm': amount,\n"
        "        'probability_of_rain': probability,\n"
        "        'rain_likely': probability >= 0.5,\n"
        "    })\n\n"
        "forecast_hourly_rainfall(['2026-03-10 06:00:00', '2026-03-10 14:00:00'])\n"
    ),
]

with open(BASE_DIR / "hourly_rainfall_forecasting.ipynb", "w") as f:
    nbf.write(nb, f)
