from pathlib import Path

import nbformat as nbf


BASE_DIR = Path(__file__).resolve().parent

nb = nbf.v4.new_notebook()

nb["cells"] = [
    nbf.v4.new_markdown_cell(
        "# Hourly Rainfall Forecasting For Irrigation\n\n"
        "This notebook trains and evaluates an hourly rainfall forecasting workflow from a dedicated "
        "`historical_weather_data_hourly.csv` file. The historical dataset stores hourly Open-Meteo signals "
        "that are relevant to rainfall behavior, while the deployed model is intentionally restricted to "
        "timestamp-derived inputs only: date, month, and time."
    ),
    nbf.v4.new_markdown_cell("## 1. Imports"),
    nbf.v4.new_code_cell(
        "import json\n"
        "from pathlib import Path\n\n"
        "import joblib\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from sklearn.linear_model import LogisticRegression, TweedieRegressor\n"
        "from sklearn.metrics import accuracy_score, brier_score_loss, mean_absolute_error, r2_score, root_mean_squared_error\n"
        "from sklearn.model_selection import TimeSeriesSplit\n"
        "from sklearn.preprocessing import StandardScaler\n\n"
        "BASE_DIR = Path.cwd()\n"
        "DATA_PATH = BASE_DIR / 'historical_weather_data_hourly.csv'\n"
        "MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.joblib'\n"
        "METRICS_PATH = BASE_DIR / 'hourly_rainfall_metrics.json'\n"
        "RAIN_THRESHOLD_MM = 0.1\n"
        "np.random.seed(42)\n"
    ),
    nbf.v4.new_markdown_cell("## 2. Load Dedicated Hourly Data"),
    nbf.v4.new_code_cell(
        "if not DATA_PATH.exists():\n"
        "    raise FileNotFoundError(\n"
        "        'historical_weather_data_hourly.csv was not found. Run fetch_weather_data.py in a network-enabled environment first.'\n"
        "    )\n\n"
        "df = pd.read_csv(DATA_PATH, parse_dates=['time'])\n"
        "df = df.sort_values('time').reset_index(drop=True)\n"
        "df['rain_mm'] = df['rain_mm'].clip(lower=0)\n"
        "df['rain_occurrence'] = (df['rain_mm'] >= RAIN_THRESHOLD_MM).astype(int)\n"
        "hourly_columns = [\n"
        "    'precipitation_probability',\n"
        "    'rain',\n"
        "    'cloud_cover',\n"
        "    'et0_fao_evapotranspiration',\n"
        "    'soil_temperature_0_to_7cm',\n"
        "    'soil_moisture_0_to_7cm',\n"
        "]\n"
        "print(df[['time', 'rain_mm', 'rain_occurrence'] + hourly_columns].head())\n"
        "print(f'Loaded {len(df):,} hourly rows from {df.time.min()} to {df.time.max()}')\n"
    ),
    nbf.v4.new_markdown_cell("## 3. Hourly Schema Check"),
    nbf.v4.new_code_cell(
        "schema_summary = df[[\n"
        "    'rain_mm',\n"
        "    'precipitation_probability',\n"
        "    'cloud_cover',\n"
        "    'et0_fao_evapotranspiration',\n"
        "    'soil_temperature_0_to_7cm',\n"
        "    'soil_moisture_0_to_7cm',\n"
        "]].describe().T\n"
        "schema_summary\n"
    ),
    nbf.v4.new_markdown_cell("## 4. Calendar Feature Engineering"),
    nbf.v4.new_code_cell(
        "def cyclical_columns(values: pd.Series, period: float, prefix: str, harmonics: int = 1) -> dict[str, np.ndarray]:\n"
        "    angles = 2 * np.pi * values.to_numpy(dtype=float) / period\n"
        "    features = {}\n"
        "    for harmonic in range(1, harmonics + 1):\n"
        "        features[f'{prefix}_sin_{harmonic}'] = np.sin(harmonic * angles)\n"
        "        features[f'{prefix}_cos_{harmonic}'] = np.cos(harmonic * angles)\n"
        "    return features\n\n"
        "def build_climatology(frame: pd.DataFrame) -> dict:\n"
        "    train = frame.copy()\n"
        "    train['month'] = train['time'].dt.month\n"
        "    train['hour'] = train['time'].dt.hour\n"
        "    train['day_of_year'] = train['time'].dt.dayofyear\n"
        "    month_hour = train.groupby(['month', 'hour'])[['rain_mm', 'rain_occurrence']].mean().reset_index()\n"
        "    doy_hour = train.groupby(['day_of_year', 'hour'])[['rain_mm', 'rain_occurrence']].mean().reset_index()\n"
        "    return {\n"
        "        'month_hour_amount': {(int(r.month), int(r.hour)): float(r.rain_mm) for r in month_hour.itertuples()},\n"
        "        'month_hour_probability': {(int(r.month), int(r.hour)): float(r.rain_occurrence) for r in month_hour.itertuples()},\n"
        "        'doy_hour_amount': {(int(r.day_of_year), int(r.hour)): float(r.rain_mm) for r in doy_hour.itertuples()},\n"
        "        'doy_hour_probability': {(int(r.day_of_year), int(r.hour)): float(r.rain_occurrence) for r in doy_hour.itertuples()},\n"
        "        'global_amount': float(train['rain_mm'].mean()),\n"
        "        'global_probability': float(train['rain_occurrence'].mean()),\n"
        "    }\n\n"
        "def build_features(timestamps: pd.Series, climatology: dict) -> pd.DataFrame:\n"
        "    ts = pd.to_datetime(timestamps)\n"
        "    month = ts.dt.month\n"
        "    hour = ts.dt.hour\n"
        "    minute = ts.dt.minute\n"
        "    day_of_year = ts.dt.dayofyear\n"
        "    day_of_week = ts.dt.dayofweek\n"
        "    day_of_month = ts.dt.day\n"
        "    year_index = ts.dt.year - ts.dt.year.min()\n"
        "    month_hour_keys = list(zip(month, hour))\n"
        "    doy_hour_keys = list(zip(day_of_year, hour))\n\n"
        "    features = {\n"
        "        'year_index': year_index.to_numpy(dtype=float),\n"
        "        'is_weekend': (day_of_week >= 5).astype(float).to_numpy(),\n"
        "        'month_hour_amount_climatology': np.array([climatology['month_hour_amount'].get(k, climatology['global_amount']) for k in month_hour_keys]),\n"
        "        'month_hour_probability_climatology': np.array([climatology['month_hour_probability'].get(k, climatology['global_probability']) for k in month_hour_keys]),\n"
        "        'doy_hour_amount_climatology': np.array([climatology['doy_hour_amount'].get(k, climatology['global_amount']) for k in doy_hour_keys]),\n"
        "        'doy_hour_probability_climatology': np.array([climatology['doy_hour_probability'].get(k, climatology['global_probability']) for k in doy_hour_keys]),\n"
        "    }\n"
        "    features.update(cyclical_columns(month, 12.0, 'month'))\n"
        "    features.update(cyclical_columns(hour + minute / 60.0, 24.0, 'hour', harmonics=2))\n"
        "    features.update(cyclical_columns(day_of_year, 365.25, 'doy', harmonics=2))\n"
        "    features.update(cyclical_columns(day_of_week, 7.0, 'dow'))\n"
        "    features.update(cyclical_columns(day_of_month, 31.0, 'dom'))\n"
        "    return pd.DataFrame(features, index=ts.index).astype(float)\n"
    ),
    nbf.v4.new_markdown_cell("## 5. Time-Based Train/Test Split"),
    nbf.v4.new_code_cell(
        "split_idx = int(len(df) * 0.8)\n"
        "train_df = df.iloc[:split_idx].copy()\n"
        "test_df = df.iloc[split_idx:].copy()\n"
        "climatology = build_climatology(train_df)\n\n"
        "X_train = build_features(train_df['time'], climatology)\n"
        "X_test = build_features(test_df['time'], climatology)\n"
        "y_train_amount = train_df['rain_mm'].to_numpy(dtype=float)\n"
        "y_test_amount = test_df['rain_mm'].to_numpy(dtype=float)\n"
        "y_train_rain = train_df['rain_occurrence'].to_numpy(dtype=int)\n"
        "y_test_rain = test_df['rain_occurrence'].to_numpy(dtype=int)\n\n"
        "month_hour_keys_test = list(zip(test_df['time'].dt.month, test_df['time'].dt.hour))\n"
        "baseline_amount = np.array([climatology['month_hour_amount'].get(k, climatology['global_amount']) for k in month_hour_keys_test])\n"
        "baseline_probability = np.array([climatology['month_hour_probability'].get(k, climatology['global_probability']) for k in month_hour_keys_test])\n\n"
        "scaler = StandardScaler()\n"
        "X_train_scaled = scaler.fit_transform(X_train)\n"
        "X_test_scaled = scaler.transform(X_test)\n\n"
        "print(f'Train rows: {len(train_df):,}')\n"
        "print(f'Test rows: {len(test_df):,}')\n"
        "print(f'Feature count: {X_train.shape[1]}')\n"
    ),
    nbf.v4.new_markdown_cell("## 6. Hyperparameter Search"),
    nbf.v4.new_code_cell(
        "def amount_metrics(y_true, y_pred):\n"
        "    return {\n"
        "        'mae_mm': float(mean_absolute_error(y_true, y_pred)),\n"
        "        'rmse_mm': float(root_mean_squared_error(y_true, y_pred)),\n"
        "        'r2': float(r2_score(y_true, y_pred)),\n"
        "    }\n\n"
        "def probability_metrics(y_true, y_prob):\n"
        "    return {\n"
        "        'brier_score': float(brier_score_loss(y_true, y_prob)),\n"
        "        'accuracy': float(accuracy_score(y_true, y_prob >= 0.5)),\n"
        "    }\n\n"
        "def search_tweedie(X, y):\n"
        "    candidates = [{'alpha': alpha, 'power': 1.5} for alpha in (0.01, 0.1, 0.5, 1.0, 2.0)]\n"
        "    splitter = TimeSeriesSplit(n_splits=5)\n"
        "    best_params = candidates[0]\n"
        "    best_score = float('inf')\n"
        "    for params in candidates:\n"
        "        scores = []\n"
        "        for train_idx, valid_idx in splitter.split(X):\n"
        "            model = TweedieRegressor(link='log', max_iter=1000, tol=1e-5, **params)\n"
        "            model.fit(X.iloc[train_idx], y[train_idx])\n"
        "            pred = model.predict(X.iloc[valid_idx]).clip(min=0)\n"
        "            scores.append(mean_absolute_error(y[valid_idx], pred))\n"
        "        score = float(np.mean(scores))\n"
        "        if score < best_score:\n"
        "            best_score = score\n"
        "            best_params = params\n"
        "    return best_params\n\n"
        "def search_logistic(X, y):\n"
        "    candidates = [{'C': c} for c in (0.1, 0.5, 1.0, 2.0, 5.0)]\n"
        "    splitter = TimeSeriesSplit(n_splits=5)\n"
        "    best_params = candidates[0]\n"
        "    best_score = float('inf')\n"
        "    for params in candidates:\n"
        "        scores = []\n"
        "        for train_idx, valid_idx in splitter.split(X):\n"
        "            model = LogisticRegression(max_iter=2000, solver='lbfgs', random_state=42, **params)\n"
        "            model.fit(X.iloc[train_idx], y[train_idx])\n"
        "            pred_prob = model.predict_proba(X.iloc[valid_idx])[:, 1]\n"
        "            scores.append(brier_score_loss(y[valid_idx], pred_prob))\n"
        "        score = float(np.mean(scores))\n"
        "        if score < best_score:\n"
        "            best_score = score\n"
        "            best_params = params\n"
        "    return best_params\n\n"
        "X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)\n"
        "best_regressor_params = search_tweedie(X_train_scaled_df, y_train_amount)\n"
        "best_classifier_params = search_logistic(X_train_scaled_df, y_train_rain)\n"
        "best_regressor_params, best_classifier_params\n"
    ),
    nbf.v4.new_markdown_cell("## 7. Train Hourly Amount And Probability Models"),
    nbf.v4.new_code_cell(
        "amount_model = TweedieRegressor(link='log', max_iter=1000, tol=1e-5, **best_regressor_params)\n"
        "probability_model = LogisticRegression(max_iter=2000, solver='lbfgs', random_state=42, **best_classifier_params)\n\n"
        "amount_model.fit(X_train_scaled, y_train_amount)\n"
        "probability_model.fit(X_train_scaled, y_train_rain)\n\n"
        "amount_pred = amount_model.predict(X_test_scaled).clip(min=0)\n"
        "probability_pred = probability_model.predict_proba(X_test_scaled)[:, 1]\n"
    ),
    nbf.v4.new_markdown_cell("## 8. Evaluate Against Month-Hour Climatology"),
    nbf.v4.new_code_cell(
        "metrics = {\n"
        "    'train_rows': int(len(train_df)),\n"
        "    'test_rows': int(len(test_df)),\n"
        "    'best_regressor_params': best_regressor_params,\n"
        "    'best_classifier_params': best_classifier_params,\n"
        "    'ml_amount': amount_metrics(y_test_amount, amount_pred),\n"
        "    'baseline_amount': amount_metrics(y_test_amount, baseline_amount),\n"
        "    'ml_probability': probability_metrics(y_test_rain, probability_pred),\n"
        "    'baseline_probability': probability_metrics(y_test_rain, baseline_probability),\n"
        "}\n\n"
        "metrics['selected_amount_model'] = (\n"
        "    'ml_amount_model'\n"
        "    if metrics['ml_amount']['mae_mm'] < metrics['baseline_amount']['mae_mm']\n"
        "    and metrics['ml_amount']['rmse_mm'] < metrics['baseline_amount']['rmse_mm']\n"
        "    else 'month_hour_climatology'\n"
        ")\n"
        "metrics['selected_probability_model'] = (\n"
        "    'ml_probability_model'\n"
        "    if metrics['ml_probability']['brier_score'] < metrics['baseline_probability']['brier_score']\n"
        "    else 'month_hour_climatology'\n"
        ")\n\n"
        "print(json.dumps(metrics, indent=2))\n"
    ),
    nbf.v4.new_markdown_cell("## 9. Export Serving Artifact"),
    nbf.v4.new_code_cell(
        "artifact = {\n"
        "    'amount_model': amount_model,\n"
        "    'probability_model': probability_model,\n"
        "    'scaler': scaler,\n"
        "    'feature_columns': list(X_train.columns),\n"
        "    'climatology': climatology,\n"
        "    'selected_amount_model': metrics['selected_amount_model'],\n"
        "    'selected_probability_model': metrics['selected_probability_model'],\n"
        "    'rain_threshold_mm': RAIN_THRESHOLD_MM,\n"
        "    'evaluation': metrics,\n"
        "}\n\n"
        "joblib.dump(artifact, MODEL_PATH)\n"
        "METRICS_PATH.write_text(json.dumps(metrics, indent=2))\n"
        "print(f'Saved {MODEL_PATH.name}')\n"
        "print(f'Saved {METRICS_PATH.name}')\n"
    ),
    nbf.v4.new_markdown_cell("## 10. Inference Helper"),
    nbf.v4.new_code_cell(
        "def forecast_hourly_rainfall(timestamps, artifact_path=MODEL_PATH):\n"
        "    package = joblib.load(artifact_path)\n"
        "    ts = pd.Series(pd.to_datetime(timestamps), name='forecast_time')\n"
        "    X = build_features(ts, package['climatology'])\n"
        "    X = X.reindex(columns=package['feature_columns'], fill_value=0.0)\n"
        "    X_scaled = package['scaler'].transform(X)\n\n"
        "    amount_ml = package['amount_model'].predict(X_scaled).clip(min=0)\n"
        "    probability_ml = package['probability_model'].predict_proba(X_scaled)[:, 1]\n"
        "    month_hour_keys = list(zip(ts.dt.month, ts.dt.hour))\n"
        "    amount_base = np.array([package['climatology']['month_hour_amount'].get(k, package['climatology']['global_amount']) for k in month_hour_keys])\n"
        "    probability_base = np.array([package['climatology']['month_hour_probability'].get(k, package['climatology']['global_probability']) for k in month_hour_keys])\n\n"
        "    amount = amount_ml if package['selected_amount_model'] == 'ml_amount_model' else amount_base\n"
        "    probability = probability_ml if package['selected_probability_model'] == 'ml_probability_model' else probability_base\n\n"
        "    return pd.DataFrame({\n"
        "        'forecast_time': ts,\n"
        "        'expected_rainfall_mm': amount,\n"
        "        'probability_of_rain': probability,\n"
        "        'rain_likely': probability >= 0.5,\n"
        "        'amount_model_used': package['selected_amount_model'],\n"
        "        'probability_model_used': package['selected_probability_model'],\n"
        "    })\n\n"
        "forecast_hourly_rainfall(['2025-04-15 06:00:00', '2025-11-10 14:00:00']).head()\n"
    ),
]

with open(BASE_DIR / "hourly_rainfall_forecasting.ipynb", "w") as f:
    nbf.write(nb, f)
