from pathlib import Path

import nbformat as nbf


BASE_DIR = Path(__file__).resolve().parent

nb = nbf.v4.new_notebook()

nb["cells"] = [
    nbf.v4.new_markdown_cell(
        "# TensorFlow Hourly Rainfall Forecasting Using Sensor Data\n\n"
        "This notebook trains an MLP rainfall forecasting model for ESP32 deployment from "
        "`historical_weather_data_hourly.csv` in the `rainfall_mlp` folder. "
        "The model predicts the rainfall amount (in mm) directly from instantaneous weather sensor readings "
        "(temperature, humidity, vapour pressure deficit, soil temperature, soil moisture, shortwave radiation, and evapotranspiration)."
    ),
    nbf.v4.new_markdown_cell("## 1. Imports"),
    nbf.v4.new_code_cell(
        "import json\n"
        "from pathlib import Path\n\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import seaborn as sns\n"
        "import tensorflow as tf\n"
        "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, confusion_matrix, ConfusionMatrixDisplay\n"
        "from tensorflow.keras import Model\n"
        "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau\n"
        "from tensorflow.keras.layers import Dense, Dropout, Input\n\n"
        "tf.keras.utils.set_random_seed(42)\n"
        "np.random.seed(42)\n\n"
        "BASE_DIR = Path.cwd()\n"
        "DATA_PATH = BASE_DIR / 'historical_weather_data_hourly.csv'\n"
        "KERAS_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.keras'\n"
        "TFLITE_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.tflite'\n"
        "CC_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.cc'\n"
        "H_MODEL_PATH = BASE_DIR / 'hourly_rainfall_forecaster.h'\n"
        "METRICS_PATH = BASE_DIR / 'hourly_rainfall_metrics.json'\n"
        "FEATURE_COLUMNS_PATH = BASE_DIR / 'hourly_feature_columns.json'\n"
        "X_MEAN_PATH = BASE_DIR / 'hourly_X_mean.npy'\n"
        "X_STD_PATH = BASE_DIR / 'hourly_X_std.npy'\n"
        "Y_AMOUNT_MEAN_PATH = BASE_DIR / 'hourly_y_amount_mean.npy'\n"
        "Y_AMOUNT_STD_PATH = BASE_DIR / 'hourly_y_amount_std.npy'\n"
        "RAIN_THRESHOLD_MM = 0.1\n"
        "C_ARRAY_NAME = 'hourly_rainfall_forecaster_tflite'\n\n"
        "FEATURES = [\n"
        "    'temperature_2m',\n"
        "    'relative_humidity_2m',\n"
        "    'vapour_pressure_deficit_kpa',\n"
        "    'soil_temperature_0_to_7cm',\n"
        "    'soil_moisture_0_to_7cm',\n"
        "    'shortwave_radiation',\n"
        "    'et0_fao_evapotranspiration_mm',\n"
        "]\n"
    ),
    nbf.v4.new_markdown_cell("## 2. Load Data"),
    nbf.v4.new_code_cell(
        "if not DATA_PATH.exists():\n"
        "    raise FileNotFoundError(\n"
        "        'historical_weather_data_hourly.csv was not found. Run fetch_hourly_weather_data.py first.'\n"
        "    )\n\n"
        "df = pd.read_csv(DATA_PATH, parse_dates=['time'])\n"
        "df = df.sort_values('time').reset_index(drop=True)\n"
        "df['precipitation_mm'] = df['precipitation_mm'].clip(lower=0)\n"
        "df = df.dropna(subset=FEATURES + ['precipitation_mm'])\n"
        "print(df[['time', 'precipitation_mm'] + FEATURES].head())\n"
        "print(f'Loaded {len(df):,} hourly rows from {df.time.min()} to {df.time.max()}')\n"
    ),
    nbf.v4.new_markdown_cell("## 3. Data Exploration"),
    nbf.v4.new_markdown_cell(
        "Before feeding the sensor metrics to our model, let's look at how precipitation correlates with our inputs. "
        "Understanding these distributions helps confirm whether our inputs carry a signal that the network can learn."
    ),
    nbf.v4.new_code_cell(
        "fig, ax = plt.subplots(figsize=(10, 8))\n"
        "sns.heatmap(df[FEATURES + ['precipitation_mm']].corr(), annot=True, cmap='coolwarm', ax=ax, fmt='.2f')\n"
        "ax.set_title('Feature Correlation Heatmap')\n"
        "plt.show()\n\n"
        "sns.pairplot(df[FEATURES + ['precipitation_mm']].sample(n=min(2000, len(df))), corner=True, diag_kind='kde')\n"
        "plt.suptitle('Pairplot of Sensor Variables and Precipitation (Sampled)', y=1.02)\n"
        "plt.show()\n"
    ),
    nbf.v4.new_markdown_cell("## 4. Time-Based Split And Scaling"),
    nbf.v4.new_markdown_cell(
        "The train-test split is chronological instead of random because forecasting must use the past to predict the future. "
        "A random split would leak future seasonal states into training and make evaluation look better than real deployment. "
        "Using the first 80% of the timeline for training and the latest 20% for testing gives a more realistic estimate of how the model behaves on unseen future months.\n\n"
        "Scaling is fit on the training window only and then reused for the test window. "
        "That keeps the preprocessing aligned with deployment, where future data statistics are not known in advance. "
        "The target precipitation amount is log-scaled before standardization because hourly rain is highly right-skewed: many dry hours and a small number of heavy-rain events. "
        "The log transform compresses those spikes so the regression loss is less dominated by a few extreme hours."
    ),
    nbf.v4.new_code_cell(
        "split_idx = int(len(df) * 0.8)\n"
        "train_df = df.iloc[:split_idx].copy()\n"
        "test_df = df.iloc[split_idx:].copy()\n\n"
        "X_train = train_df[FEATURES].to_numpy(dtype=np.float32)\n"
        "X_test = test_df[FEATURES].to_numpy(dtype=np.float32)\n"
        "y_train_amount = train_df['precipitation_mm'].to_numpy(dtype=np.float32)\n"
        "y_test_amount = test_df['precipitation_mm'].to_numpy(dtype=np.float32)\n\n"
        "X_mean = X_train.mean(axis=0)\n"
        "X_std = X_train.std(axis=0)\n"
        "X_std[X_std == 0] = 1e-6\n"
        "X_train_scaled = (X_train - X_mean) / X_std\n"
        "X_test_scaled = (X_test - X_mean) / X_std\n\n"
        "y_train_amount_log = np.log1p(y_train_amount)\n"
        "y_amount_mean = float(y_train_amount_log.mean())\n"
        "y_amount_std = float(y_train_amount_log.std())\n"
        "if y_amount_std == 0:\n"
        "    y_amount_std = 1e-6\n"
        "y_train_amount_scaled = ((y_train_amount_log - y_amount_mean) / y_amount_std).astype(np.float32)\n\n"
        "np.save(X_MEAN_PATH, X_mean)\n"
        "np.save(X_STD_PATH, X_std)\n"
        "np.save(Y_AMOUNT_MEAN_PATH, np.array([y_amount_mean], dtype=np.float32))\n"
        "np.save(Y_AMOUNT_STD_PATH, np.array([y_amount_std], dtype=np.float32))\n"
        "FEATURE_COLUMNS_PATH.write_text(json.dumps(FEATURES, indent=2))\n"
        "print(f'Train rows: {len(train_df):,}, test rows: {len(test_df):,}')\n"
        "print(f'Feature count: {X_train_scaled.shape[1]}')\n"
    ),
    nbf.v4.new_code_cell(
        "fig, axes = plt.subplots(1, 2, figsize=(15, 5), constrained_layout=True)\n\n"
        "axes[0].plot(df['time'], df['precipitation_mm'], color='tab:blue', linewidth=0.8)\n"
        "axes[0].axvline(df.loc[split_idx, 'time'], color='tab:red', linestyle='--', label='Train/test split')\n"
        "axes[0].set_title('Chronological Split On Rainfall Timeline')\n"
        "axes[0].set_xlabel('Timestamp')\n"
        "axes[0].set_ylabel('Precipitation (mm)')\n"
        "axes[0].legend()\n\n"
        "axes[1].hist(y_train_amount, bins=50, alpha=0.65, label='Raw train target', color='tab:blue')\n"
        "axes[1].hist(np.log1p(y_train_amount), bins=50, alpha=0.65, label='log1p(train target)', color='tab:orange')\n"
        "axes[1].set_title('Why Log-Scale The Precipitation Target')\n"
        "axes[1].set_xlabel('Target value')\n"
        "axes[1].set_ylabel('Count')\n"
        "axes[1].legend()\n"
        "plt.show()\n\n"
    ),
    nbf.v4.new_markdown_cell("## 5. TensorFlow MLP Model"),
    nbf.v4.new_code_cell(
        "inputs = Input(shape=(X_train_scaled.shape[1],), name='sensor_features')\n"
        "x = Dense(32, activation='relu')(inputs)\n"
        "x = Dense(16, activation='relu')(x)\n"
        "amount_output = Dense(1, name='amount_output')(x)\n\n"
        "model = Model(inputs=inputs, outputs=amount_output)\n"
        "model.compile(\n"
        "    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n"
        "    loss='mse',\n"
        ")\n"
        "model.summary()\n"
    ),
    nbf.v4.new_markdown_cell("## 6. Train"),
    nbf.v4.new_code_cell(
        "callbacks = [\n"
        "    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),\n"
        "]\n\n"
        "history = model.fit(\n"
        "    X_train_scaled,\n"
        "    y_train_amount_scaled,\n"
        "    validation_split=0.15,\n"
        "    epochs=40,\n"
        "    batch_size=256,\n"
        "    verbose=1,\n"
        "    callbacks=callbacks,\n"
        ")\n\n"
        "print(f\"Training stopped after {len(history.history['loss'])} epochs.\")\n"
        "print(f\"Best val_loss: {min(history.history['val_loss']):.4f}\")\n"
    ),
    nbf.v4.new_markdown_cell("## 7. Evaluate"),
    nbf.v4.new_code_cell(
        "amount_pred_scaled = model.predict(X_test_scaled, verbose=0)\n"
        "amount_pred_scaled = amount_pred_scaled.reshape(-1)\n"
        "amount_pred = np.expm1((amount_pred_scaled * y_amount_std) + y_amount_mean).clip(min=0)\n"
        "rainy_mask = y_test_amount >= RAIN_THRESHOLD_MM\n\n"
        "def amount_metrics(y_true, y_pred):\n"
        "    rainy_true = y_true[rainy_mask]\n"
        "    rainy_pred = y_pred[rainy_mask]\n"
        "    return {\n"
        "        'mae_mm': float(mean_absolute_error(y_true, y_pred)),\n"
        "        'rmse_mm': float(mean_squared_error(y_true, y_pred)**0.5),\n"
        "        'r2': float(r2_score(y_true, y_pred)),\n"
        "        'rainy_hours_count': int(rainy_mask.sum()),\n"
        "        'rainy_mae_mm': float(mean_absolute_error(rainy_true, rainy_pred)) if len(rainy_true) > 0 else 0.0,\n"
        "        'rainy_rmse_mm': float(mean_squared_error(rainy_true, rainy_pred)**0.5) if len(rainy_true) > 0 else 0.0,\n"
        "    }\n\n"
        "metrics = {\n"
        "    'train_rows': int(len(train_df)),\n"
        "    'test_rows': int(len(test_df)),\n"
        "    'feature_columns': FEATURES,\n"
        "    'amount_models': {\n"
        "        'mlp_sensors': amount_metrics(y_test_amount, amount_pred),\n"
        "    },\n"
        "    'selected_amount_model': 'mlp_sensors',\n"
        "}\n"
        "print(json.dumps(metrics, indent=2))\n"
    ),
    nbf.v4.new_code_cell(
        "fig, axes = plt.subplots(1, 2, figsize=(15, 6), constrained_layout=True)\n\n"
        "axes[0].scatter(y_test_amount, amount_pred, alpha=0.3, color='tab:blue')\n"
        "axes[0].plot([0, y_test_amount.max()], [0, y_test_amount.max()], 'r--', label='Ideal Fit')\n"
        "axes[0].set_title('Actual vs Predicted Precipitation')\n"
        "axes[0].set_xlabel('Actual Precipitation (mm)')\n"
        "axes[0].set_ylabel('Predicted Precipitation (mm)')\n"
        "axes[0].legend()\n\n"
        "error = amount_pred - y_test_amount\n"
        "axes[1].hist(error, bins=50, color='tab:red', alpha=0.7)\n"
        "axes[1].axvline(0, color='black', linestyle='dashed', linewidth=1)\n"
        "axes[1].set_title('Prediction Error Distribution')\n"
        "axes[1].set_xlabel('Error (Predicted - Actual) mm')\n"
        "axes[1].set_ylabel('Frequency')\n"
        "plt.show()\n\n"
        "fig, ax = plt.subplots(figsize=(15, 5), constrained_layout=True)\n"
        "plot_slice = slice(0, 200)\n"
        "time_slice = test_df['time'].iloc[plot_slice]\n"
        "ax.plot(time_slice, y_test_amount[plot_slice], label='Actual', marker='.', color='tab:blue')\n"
        "ax.plot(time_slice, amount_pred[plot_slice], label='Predicted', marker='x', color='tab:orange', alpha=0.7)\n"
        "ax.set_title('Actual vs Predicted (First 200 hours of Test Set)')\n"
        "ax.set_ylabel('Precipitation (mm)')\n"
        "ax.legend()\n"
        "plt.show()\n\n"
        "cm = confusion_matrix(y_test_amount >= RAIN_THRESHOLD_MM, amount_pred >= RAIN_THRESHOLD_MM)\n"
        "disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Rain', 'Rain'])\n"
        "fig, ax = plt.subplots(figsize=(6, 6))\n"
        "disp.plot(ax=ax, cmap='Blues', colorbar=False)\n"
        "ax.set_title('Confusion Matrix for Rain Occurrence (>= 0.1 mm)')\n"
        "plt.show()\n"
    ),
    nbf.v4.new_markdown_cell("## 8. Export Keras, TFLite, And ESP32 Artifacts"),
    nbf.v4.new_code_cell(
        "def convert_tflite_to_c_array(tflite_path: Path, c_file_path: Path, h_file_path: Path, array_name: str):\n"
        "    tflite_content = tflite_path.read_bytes()\n"
        "    hex_array = [f'0x{byte:02x}' for byte in tflite_content]\n\n"
        "    with c_file_path.open('w') as c_file:\n"
        "        c_file.write(f'#include \"{h_file_path.name}\"\\n\\n')\n"
        "        c_file.write(f'const unsigned char {array_name}[] = {{\\n')\n"
        "        for idx in range(0, len(hex_array), 12):\n"
        "            c_file.write('  ' + ', '.join(hex_array[idx:idx + 12]) + ',\\n')\n"
        "        c_file.write('};\\n\\n')\n"
        "        c_file.write(f'const int {array_name}_len = {len(tflite_content)};\\n')\n\n"
        "    with h_file_path.open('w') as h_file:\n"
        "        guard = h_file_path.stem.upper() + '_H'\n"
        "        h_file.write(f'#ifndef {guard}\\n')\n"
        "        h_file.write(f'#define {guard}\\n\\n')\n"
        "        h_file.write(f'extern const unsigned char {array_name}[];\\n')\n"
        "        h_file.write(f'extern const int {array_name}_len;\\n\\n')\n"
        "        h_file.write(f'#endif  // {guard}\\n')\n\n"
        "model.save(KERAS_MODEL_PATH)\n"
        "converter = tf.lite.TFLiteConverter.from_keras_model(model)\n"
        "tflite_model = converter.convert()\n"
        "TFLITE_MODEL_PATH.write_bytes(tflite_model)\n"
        "convert_tflite_to_c_array(TFLITE_MODEL_PATH, CC_MODEL_PATH, H_MODEL_PATH, C_ARRAY_NAME)\n"
        "METRICS_PATH.write_text(json.dumps(metrics, indent=2))\n\n"
        "print(f'Saved {KERAS_MODEL_PATH.name}')\n"
        "print(f'Saved {TFLITE_MODEL_PATH.name} ({len(tflite_model)} bytes)')\n"
        "print(f'Saved {CC_MODEL_PATH.name}')\n"
        "print(f'Saved {H_MODEL_PATH.name}')\n"
        "print(f'Saved {METRICS_PATH.name}')\n"
    ),
    nbf.v4.new_markdown_cell("## 9. Inference Helper"),
    nbf.v4.new_code_cell(
        "VPD_COLUMN = 'vapour_pressure_deficit_kpa'\n"
        "RAW_SENSOR_FEATURES = [feature for feature in FEATURES if feature != VPD_COLUMN]\n\n"
        "def calculate_vapour_pressure_deficit_kpa(temperature_c, relative_humidity_percent):\n"
        "    temperature = np.asarray(temperature_c, dtype=np.float32)\n"
        "    relative_humidity = np.clip(np.asarray(relative_humidity_percent, dtype=np.float32), 0.0, 100.0)\n"
        "    saturation_vapour_pressure = 0.6108 * np.exp((17.27 * temperature) / (temperature + 237.3))\n"
        "    return np.maximum(saturation_vapour_pressure * (1.0 - (relative_humidity / 100.0)), 0.0)\n\n"
        "def prepare_sensor_readings(sensor_readings):\n"
        "    readings = pd.DataFrame(sensor_readings)\n"
        "    if all(isinstance(column, int) for column in readings.columns):\n"
        "        if readings.shape[1] == len(FEATURES):\n"
        "            readings.columns = FEATURES\n"
        "        elif readings.shape[1] == len(RAW_SENSOR_FEATURES):\n"
        "            readings.columns = RAW_SENSOR_FEATURES\n"
        "        else:\n"
        "            raise ValueError(f'Expected {len(FEATURES)} deployed features or {len(RAW_SENSOR_FEATURES)} raw sensor features, got {readings.shape[1]}.')\n\n"
        "    if VPD_COLUMN not in readings.columns:\n"
        "        readings[VPD_COLUMN] = calculate_vapour_pressure_deficit_kpa(\n"
        "            readings['temperature_2m'],\n"
        "            readings['relative_humidity_2m'],\n"
        "        )\n\n"
        "    missing = [feature for feature in FEATURES if feature not in readings.columns]\n"
        "    if missing:\n"
        "        raise ValueError(f'Missing required feature columns: {missing}')\n\n"
        "    return readings[FEATURES].astype(np.float32)\n\n"
        "def forecast_hourly_rainfall(sensor_readings):\n"
        "    readings = prepare_sensor_readings(sensor_readings)\n"
        "    X_future = readings.to_numpy(dtype=np.float32)\n"
        "    X_future_scaled = (X_future - X_mean) / X_std\n"
        "    amount_scaled = model.predict(X_future_scaled, verbose=0)\n"
        "    amount_scaled = amount_scaled.reshape(-1)\n"
        "    amount_log = (amount_scaled * y_amount_std) + y_amount_mean\n"
        "    amount = np.expm1(np.maximum(amount_log, 0.0))\n"
        "    return readings.assign(predicted_precipitation_mm=amount)[\n"
        "        [VPD_COLUMN, 'predicted_precipitation_mm']\n"
        "    ]\n\n"
        "forecast_hourly_rainfall([\n"
        "    {\n"
        "        'temperature_2m': 25.0,\n"
        "        'relative_humidity_2m': 60.0,\n"
        "        'soil_temperature_0_to_7cm': 24.0,\n"
        "        'soil_moisture_0_to_7cm': 0.290,\n"
        "        'shortwave_radiation': 500.0,\n"
        "        'et0_fao_evapotranspiration_mm': 0.5,\n"
        "    },\n"
        "    {\n"
        "        'temperature_2m': 20.0,\n"
        "        'relative_humidity_2m': 90.0,\n"
        "        'soil_temperature_0_to_7cm': 19.0,\n"
        "        'soil_moisture_0_to_7cm': 0.300,\n"
        "        'shortwave_radiation': 100.0,\n"
        "        'et0_fao_evapotranspiration_mm': 0.1,\n"
        "    },\n"
        "])\n"
    ),
]

with open(BASE_DIR / "hourly_rainfall_forecasting.ipynb", "w") as f:
    nbf.write(nb, f)
